#!/usr/bin/env bash
#This is a script that 127.0.0.2 and 8.8.8.8 to localhost and facebook.com
cp /etc/hosts /etc/hosts.bak
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
